[build-system]
requires = ["maturin>=1.2,<2.0"]
build-backend = "maturin"

[project]
name = "verbs-examples"
version = "0.1.0"
description = ''
readme = "README.md"
requires-python = ">=3.8"
keywords = []
authors = [
  { name = "Jordan", email = "jordan@simtopia.ai" },
]
classifiers = [
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Rust",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "verbs@git+ssh://git@github.com/simtopia/rusty_venture.git"
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.envs.dev.scripts]
run = "python uniswap_gbm.py"
lint = "pre-commit install && pre-commit run --all-files"
