[build-system]
requires = ["maturin>=1.2,<2.0"]
build-backend = "maturin"

[project]
name = "verbs-examples"
version = "0.1.0"
description = "VERBS simulation examples"
readme = "README.md"
requires-python = ">=3.8"
keywords = []
authors = [
  { name = "Jordan", email = "jordan@simtopia.ai" },
  { name = "Marc", email = "marc@simtopia.ai"}
]
classifiers = [
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Rust",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "verbs@git+ssh://git@github.com/simtopia/verbs.git",
  "matplotlib"
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.envs.dev]
dependencies = [
  "pre-commit >= 3.3.3",
]

[tool.hatch.envs.dev.scripts]
lint = "pre-commit install && pre-commit run --all-files"

[tool.hatch.envs.examples.scripts]
uniswap = "python sim_uniswap_gbm.py {args}"
aave = "python sim_aave_uniswap.py {args}"
